### ISSUE TITLE
Checklist - CSS/JS Markup

### ISSUE THREAD

**Issue by diogosp** [brainwp/template-issues#4]
- [ ] HTML has passed validation (or known issues noted)
- [ ] CSS has passed validation (or known issues noted)
- [ ] Bonus: CSS tested on CSS Lint (to hurt your feelings)
- [ ] Site links have been tested and resolve correctly
- [ ] JavaScript is error free
