### ISSUE TITLE
Checklist - Accessibility

### ISSUE THREAD

**Issue by diogosp** [brainwp/template-issues#5]
- [ ] Website meets appropriate level of WCAG compliance
- [ ] ARIA Landmark Roles specified
- [ ] Semantic headings and structure used
- [ ] Links are clearly recognisable and have :focus state
- [ ] Images use appropriate ALT text
- [ ] Alternatives provided for users with Javascript disabled
- [ ] Forms have logical layout
- [ ] Associated label for all form controls
- [ ] Colour contrast tested
- [ ] Website accessibility has been checked with Total Validator Pro or WAVE and issues resolved (exceptions noted)
