### ISSUE TITLE
Checklist - Forms, Search and Fields

### ISSUE THREAD

**Issue by diogosp** [brainwp/template-issues#6]
- [ ] Forms have been tested and processed correctly
- [ ] Required fields have been tested
- [ ] Review input validation (min/max lengths, character limits)
- [ ] Forms send to the correct recipient
- [ ] Forms have confirmation URL or event tracking so submissions can be tracked
- [ ] Forms process correctly with JavaScript disabled
- [ ] Website search and search results function correctly
