### ISSUE TITLE
Checklist - optimisation 

### ISSUE THREAD

**Issue by diogosp** [brainwp/template-issues#7]
- [ ] Images have been optimised
- [ ] CSS is minified and combined
- [ ] JavaScript is minified and combined (as much as possible)
- [ ] Enable gzip compression
- [ ] Ensure only necessary fonts, weights and character sets are installed
- [ ] Run Google speed test and optimise accordingly (record score and known issues)
- [ ] Run Web page test and optimise accordingly (record results)
- [ ] Incorporate CDN / Caching as required
