### ISSUE TITLE
Checklist - Security

### ISSUE THREAD

**Issue by diogosp** [brainwp/template-issues#8]
- [ ] Secure areas are locked down and not accessible by search engines
- [ ] Default CMS login URL is changed
- [ ] Default CMS username is changed
- [ ] SSL Certificate is requested
