### ISSUE TITLE
Checklist - Post Launch

### ISSUE THREAD

**Issue by diogosp** [brainwp/template-issues#9]
- [ ] Ensure site is visible to search engines - Check WP Settings
- [ ] SSL certificates successfully installed
- [ ] Images, media and links reference live URL (Plugin)
- [ ] Webfonts integrated and working correctly on live site
- [ ] Webfonts set to production (as required)
- [ ] 301 redirects are in place and working correctly (Site Templates)
- [ ] Website URL has been submitted to Google
- [ ] Generate a new sitemap.xml and upload to root
- [ ] Site added to Google Webmaster tools and sitemap submitted
- [ ] Analytics has been setup and integrated into website (If applicable)
